name: Validate Production PR Workflow

on:
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Create .env.test file'
        run: |
          touch .env.test
          echo OPEN_WEATHER_API_KEY=${{ secrets.OPEN_WEATHER_API_KEY }} >> .env.test
          echo OPEN_WEATHER_BASE_URL=${{ secrets.OPEN_WEATHER_BASE_URL }} >> .env.test

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.4.1'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run unit tests
        run: yarn test

      - name: Run e2e tests
        run: yarn test:e2e
